#nome = "luiz"
#idade = 23
#casado = True
#altura = 1.80

#print(type(nome))
#print(type(idade))
#print(type(casado))
#print(type(altura))

#O que o código abaixo exibe?

#nome = "Luiz"
#idade = 23
#formato = '{n} tem {i} anos'
#print(formato.format(n=nome, i=idade))

#nome = "Luiz"
#idade = 23
#formato = f'{nome} tem {idade:.2f} anos'
#print(formato.format(nome, idade))

numero_1 = 10
numero_2 = 20
resultado = numero_1 * numero_2
print(resultado)
